[package]
name = "ds-rs"
version = "0.1.0" # TODO: use the workspace version
edition = "2024" # TODO: use the workspace edition
description = "Powerful library to control nVidia DeepStream AI processing framework"

[features]
default = ["std"]
std = []
logging = ["gstreamer/log"]
serde = ["gstreamer/serde"]
gst_v1_16 = ["gstreamer/v1_16"]
gst_v1_18 = ["gstreamer/v1_18"]
gst_v1_20 = ["gstreamer/v1_20"]
gst_v1_22 = ["gstreamer/v1_22"]
gst_v1_24 = ["gstreamer/v1_24"]
gst_v1_26 = ["gstreamer/v1_26"]
gst_v1_28 = ["gstreamer/v1_28"]


[dependencies]
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
gstreamer.workspace = true
gstreamer-app.workspace = true
gstreamer-video.workspace = true
log = "0.4.27"
once_cell = "1.21.3"
rand.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"

# CPU Vision Backend dependencies (placeholders for future implementation)
# ort = { version = "1.16.3", features = ["load-dynamic"] }  # TODO: Add when implementing ONNX
image = "0.25"
# imageproc = "0.25"  # TODO: Add when implementing image processing
nalgebra = "0.34.0"
# ndarray = "0.16"  # TODO: Add when implementing tensor operations

[[bin]]
name = "ds-app"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.8"
