log_level = "info"

[server]
port = 8554
address = "127.0.0.1"
max_connections = 100

[[sources]]
name = "test-smpte"
type = "test_pattern"
pattern = "smpte"

[sources.resolution]
width = 1920
height = 1080

[sources.framerate]
numerator = 30
denominator = 1

format = "i420"
is_live = true

[[sources]]
name = "test-ball"
type = "test_pattern"
pattern = "ball"

[sources.resolution]
width = 1280
height = 720

[sources.framerate]
numerator = 25
denominator = 1

format = "i420"
is_live = true

[[sources]]
name = "test-snow"
type = "test_pattern"
pattern = "snow"

[sources.resolution]
width = 640
height = 480

[sources.framerate]
numerator = 15
denominator = 1

format = "i420"
is_live = true
